### ISSUE TITLE
Rimworld installed on another drive

### ISSUE THREAD

**Issue by shaunie1996** [Chris24T/RimLists#4]
the .exe throws an error, then closes. I was able to read the error by using powershell, and I am now attempting to wrap my head around the python method, as described in a comment, here  https://www.reddit.com/r/RimWorld/comments/116h5qv/script_to_convert_steam_workshop_collection_to/
Given I have exactly 0 technical know how, it would be great if you'd be willing to update the script to solve this issue.
The full error 
Please enter your full RimWorld install path: D:\SteamLibrary\steamapps\common\RimWorld
Traceback (most recent call last):
  File "main.py", line 180, in <module>
  File "main.py", line 124, in findModPackageIds
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c:\\program files (x86)\\steam\\steamapps\\workshop\\content\\294100'
[15220] Failed to execute script 'main' due to unhandled exception!

**Comment by That-Lamer** [comment]
Yes, steam installs workshop mods on the same drive as the game, so this program should be using the install path with ..\steamapps\workshop\content\294100 instead of the default C: path.

Edit: Really though the exe just needs to get updated with the py script, which does work. For anyone reading this in the future, install the latest version of python (currently 3.13) and then from wherever  you downloaded the main.py file from the main github page, right click an empty space in that folder within explorer and open powershell/terminal. Follow the readme instructions of doing the 3 pip commands, then do "python main.py". Follow instructions from there.

**Comment by DrDr-dev** [comment]
For me Rimworld was installed on another disk so I needed to customize the script in row 72 a little but just change the method: 

def get_steam_install_path():
    global steam_install_path
    print("Unable to find Steam install directory")
    steam_install_path = input("Please enter Steam install path: ")

and enter if prompted your steamlibary eg: (Please enter Steam install path: D:\SteamLibrary)
